name: Paul Lunows Interaktiondesigner
title: Paul Lunows Interaktiondesigner
future: true
markdown: kramdown
highlighter: rouge
permalink: '/:year/:title'
pagination:
  enabled: true
  per_page: 15
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

url: http://www.interaktionsdesigner.de
gems:
  - jekyll-redirect-from
  - jekyll-paginate-v2