name: Paul Lunows Interaktiondesigner
title: Paul Lunows Interaktiondesigner
markdown: redcarpet
highlighter: pygments
permalink: '/:year/:title'
paginate: 15
paginate_path: "page/:num"
url: http://www.interaktionsdesigner.de
gems:
  - jekyll-redirect-from